/**
 * Genera `src/user_space/user-engine-reports.generated.ts` a partir de los `engine_report.json`
 * descubiertos en disco (autodescubrimiento sin registro manual).
 */
import { writeFile } from "fs/promises";
import path from "path";
import {
  discoverUserEngineReports,
  resolveFiferLandingRoot,
} from "../src/core/user-engine-discovery";

async function main() {
  const root = resolveFiferLandingRoot(process.cwd());
  const { reports, issues } = await discoverUserEngineReports(undefined, root);
  if (issues.length) {
    console.warn("[fifer:discover-engines] Avisos:", issues);
  }
  const outPath = path.join(root, "src", "user_space", "user-engine-reports.generated.ts");
  const json = JSON.stringify(reports, null, 2);
  const file = `/* eslint-disable */
// AUTO-GENERATED by scripts/discover-user-engines.ts — no editar a mano.
import type { UserEngineReport } from "@/schemas/engine-report.schema";

export const USER_ENGINE_REPORTS: Partial<Record<string, UserEngineReport>> = ${json};
`;
  await writeFile(outPath, file, "utf8");
  console.log(`[fifer:discover-engines] Escrito ${outPath} (${Object.keys(reports).length} engines).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
