/* eslint-disable */
// AUTO-GENERATED by scripts/discover-user-engines.ts — no editar a mano.
import type { UserEngineReport } from "@/schemas/engine-report.schema";

export const USER_ENGINE_REPORTS: Partial<Record<string, UserEngineReport>> = {
  "u-user-id-mock-sample-scraper": {
    "id": "sample-scraper",
    "name": "Sample Scraper",
    "function": "execute",
    "risk": "high",
    "inputs": [
      {
        "id": "providerApiKey",
        "label": "API Key del proveedor (BYOK)",
        "type": "api_key"
      },
      {
        "id": "targetUrl",
        "label": "URL a inspeccionar",
        "type": "url"
      },
      {
        "id": "selectors",
        "label": "Selectores opcionales",
        "type": "json"
      }
    ],
    "outputs": [
      {
        "id": "normalizedRows",
        "label": "Filas normalizadas FIFER",
        "type": "object[]"
      },
      {
        "id": "engineManifest",
        "label": "Fragmento de manifiesto",
        "type": "partial_manifest"
      }
    ],
    "version": "0.1.0"
  }
};
